project_id = "mcvohdpjzihslxkpajqd"

[functions.ai-chat]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.discover-sources]
verify_jwt = true

[functions.change-password]
verify_jwt = true

[functions.youtube-transcript]
verify_jwt = true

[functions.generate-summary]
verify_jwt = true
